general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold" }
italic = { family = "0xProto Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 8
padding.y = 8
decorations = "None"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
